import { beforeAll, describe, expect, it } from "vitest";

import { readFileSync } from "node:fs";
import { join } from "node:path";

import { autoReplyReason } from "@metavchim/shared";

import { AUTO_SUBMITTED_HEADER, EmailService } from "./email.service";
import { PlatformSettingsService } from "./platform-settings.service";
import { PrismaService } from "./prisma.service";
import { platformAdminRecipients } from "./platform-admin-notifier.service";

describe("נמעני התראת הפלטפורמה", () => {
  it("מאחד את המנהלים עם הכתובות הנוספות", () => {
    expect(platformAdminRecipients(["a@x.co.il", "b@x.co.il"], ["desk@x.co.il"])).toEqual([
      "a@x.co.il",
      "b@x.co.il",
      "desk@x.co.il",
    ]);
  });

  /*
   * ‎**כתובת התמיכה היא לרוב גם כתובת של מנהל.** בלי איחוד היה מגיע
   * לשם אותו מייל פעמיים — בדיוק הצורה שגורמת לאנשים לכבות התראות.
   */
  it("כתובת שמופיעה פעמיים מקבלת עותק אחד", () => {
    expect(platformAdminRecipients(["a@x.co.il"], ["a@x.co.il"])).toEqual(["a@x.co.il"]);
  });

  it("רישיות אינה יוצרת נמען שני", () => {
    expect(platformAdminRecipients(["a@x.co.il"], [" A@X.co.il "])).toEqual(["a@x.co.il"]);
  });

  /*
   * ההגדרה מגיעה ממי שהקליד אותה במסך, ולכן היא יכולה להיות ריקה,
   * לא מוגדרת, או טקסט שאינו כתובת. שליחה לכזו נכשלת אצל הספק —
   * כלומר קריאת רשת מיותרת ושורת אזהרה ביומן על כל פנייה.
   */
  it("ריק, `undefined` ומה שאינו כתובת אינם נמענים", () => {
    expect(platformAdminRecipients([], ["", null, undefined, "לא כתובת"])).toEqual([]);
  });

  /*
   * ‎**הכתובת נשמרת כפי שנראתה.** החלק שלפני ה-`@` רגיש לרישיות
   * רשמית; איחוד הוא סיבה לזהות כפילות, לא רשות לשנות כתובת.
   */
  it("הכתובת המקורית היא זו שנשלחת", () => {
    expect(platformAdminRecipients([], ["Dana.Levi@X.co.il"])).toEqual(["Dana.Levi@X.co.il"]);
  });
});

/**
 * ‎**הלולאה שקרתה בייצור.**
 *
 * התראת „פנייה חדשה” נשלחה ל-`supportEmail`; הכתובת הזאת מנותבת
 * לוובהוק הנכנס; ההתראה נקלטה כהודעה חדשה על אותה פנייה — והפעילה
 * התראה נוספת. מאות הודעות על פנייה אחת, אצל לקוח, תוך שעות.
 *
 * ‎`provider_message_id` לא עצר את זה ולא היה אמור: כל סיבוב הוא
 * הודעה **חדשה** עם מזהה חדש. הדה-דופליקציה מגינה מפני מסירה חוזרת
 * של אותה הודעה, לא מפני ייצור הודעות.
 *
 * מה שעוצר היא הכותרת — ולכן היא נבדקת כאן **מקצה לקצה**: הערך
 * שהשירות שולח בפועל מוזן ל-`autoReplyReason`, ונדרש שייפול.
 * הצהרה שהשירות „מוסיף כותרת” הייתה עוברת גם אם הצד הנכנס אינו
 * מכיר אותה.
 */
describe("שובר הלולאה", () => {
  it("הכותרת שההתראה נושאת היא זו שהצד הנכנס מפיל", () => {
    const reason = autoReplyReason({
      subject: "#38 פנייה חדשה במייל: משהו",
      headers: [{ name: AUTO_SUBMITTED_HEADER.Name, value: AUTO_SUBMITTED_HEADER.Value }],
    });
    expect(reason, "הצד הנכנס אינו מפיל את ההתראה — הלולאה חוזרת").not.toBeNull();
  });

  /*
   * ‎`auto-submitted: no` פירושו מפורשות „אדם”, ולכן ערך כזה **חייב**
   * להיקלט. הבדיקה כאן כדי שהתיקון לא ייצא מגדרו ויפיל פניות אמיתיות.
   */
  it("הודעה של אדם אינה נופלת בגלל התיקון", () => {
    expect(
      autoReplyReason({ subject: "שאלה על המערכת", headers: [] }),
      "פנייה רגילה נדחתה",
    ).toBeNull();
    expect(
      autoReplyReason({
        subject: "שאלה על המערכת",
        headers: [{ name: "Auto-Submitted", value: "no" }],
      }),
      "„auto-submitted: no” פירושו אדם",
    ).toBeNull();
  });
});

/**
 * ‎**שלושת הקצוות של שובר הלולאה — כל אחד בנפרד.**
 *
 * הבדיקה שמעל מוכיחה שה**ערך** הוא כזה שהצד הנכנס מפיל. היא אינה
 * מוכיחה שהוא באמת נשלח, ובדיקת שבירה הראתה בדיוק את זה: מחיקת
 * ‎`autoGenerated: true` מהמודיע ומחיקת הכותרת מגוף הבקשה **עברו
 * שתיהן**. שער שמאשר קוד שאינו שולח את מה שהוא מבטיח הוא בדיוק
 * הסוג שגרם לתקלה מלכתחילה.
 */
describe("הכותרת באמת יוצאת", () => {
  /*
   * ‎`loadEnv()` נקרא בדרך אל הספק ודורש תצורה שלמה. הערכים מזויפים
   * ובכוונה — הבדיקה אינה נוגעת ברשת: `fetch` מוחלף.
   */
  beforeAll(() => {
    process.env["WEB_ORIGIN"] ??= "https://test.invalid";
    process.env["DATABASE_URL"] ??= "postgresql://t:t@localhost:5432/t";
    process.env["DIRECT_DATABASE_URL"] ??= "postgresql://t:t@localhost:5432/t";
    process.env["REDIS_URL"] ??= "redis://localhost:6379";
    process.env["DATA_ENCRYPTION_KEY"] ??= "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
    process.env["PHONE_HASH_KEY"] ??= "test-phone-hash-key-not-a-real-secret-0000";
  });

  function fakeService(): { email: EmailService; sent: Record<string, unknown>[] } {
    const sent: Record<string, unknown>[] = [];
    const settings = {
      get: async (key: string) =>
        key === "postmarkServerToken" ? "tok" : key === "emailFrom" ? "a@b.co" : undefined,
    } as unknown as PlatformSettingsService;
    const prisma = {} as unknown as PrismaService;
    globalThis.fetch = (async (_url: string, init: { body: string }) => {
      sent.push(JSON.parse(init.body) as Record<string, unknown>);
      return { ok: true, status: 200, text: async () => "" } as Response;
    }) as unknown as typeof fetch;
    return { email: new EmailService(settings, prisma), sent };
  }

  it("‏`autoGenerated` מגיע עד גוף הבקשה לספק", async () => {
    const { email, sent } = fakeService();
    await email.send("admin@x.co", "נושא", { paragraphs: ["גוף"] }, { autoGenerated: true });
    expect(sent).toHaveLength(1);
    expect(sent[0]?.["Headers"], "הכותרת לא נשלחה בפועל").toEqual([AUTO_SUBMITTED_HEADER]);
  });

  /* מייל ללקוח הוא שיחה — סימונו כאוטומטי פוגע במסירה ובשרשור */
  it("מייל רגיל אינו נושא אותה", async () => {
    const { email, sent } = fakeService();
    await email.send("buyer@x.co", "נושא", { paragraphs: ["גוף"] });
    expect(sent[0]?.["Headers"]).toBeUndefined();
  });
});

/**
 * ‎**וההתראה עצמה מבקשת אותה** — הקצה שנשאר.
 *
 * מבני ולא התנהגותי: הרצת `notify` דורשת `loadEnv` ורשימת מנהלים,
 * וההצהרה שנשמרת כאן היא צורה — שהמודיע מסמן כל התראה, בלי יוצא.
 */
describe("כל התראה מסומנת", () => {
  const SERVICE = readFileSync(
    join(import.meta.dirname, "platform-admin-notifier.service.ts"),
    "utf8",
  ).replace(/\/\*[\s\S]*?\*\//gu, "");

  it("המודיע מבקש את הכותרת בכל שליחה", () => {
    expect(SERVICE, "התראה נשלחת בלי הסימון").toContain("autoGenerated: true");
  });

  /*
   * ההגנה השנייה: אין טעם לשלוח לתיבה שמזינה אותנו, גם כשהכותרת
   * במקומה. זו הכתובת שההתראה נחתה בה בפועל בתקלה.
   */
  it("כתובת הקליטה של התמיכה אינה נמענת", () => {
    expect(SERVICE).toContain('this.settings.get("supportInboundAddress")');
    expect(SERVICE, "הכתובת אינה מסוננת מהנמענים").toMatch(/toLowerCase\(\) !== inbound/u);
  });
});
