import {
  Injectable,
  Logger,
  type OnModuleDestroy,
  type OnModuleInit,
} from "@nestjs/common";
import {
  forumActivityEmail,
  forumLaunchEmail,
  isForumNotificationType,
  jerusalemWallParts,
  parseForumPrefs,
  type ForumMailItem,
  type ForumPrefs,
} from "@metavchim/shared";
import { loadEnv } from "../../config/env";
import { EmailService } from "../../core/email.service";
import { PrismaService } from "../../core/prisma.service";

/**
 * המייל של הפורום — **הערוץ השלישי של אותן התראות.**
 *
 * הפעמון והוואטסאפ כבר מרימים את שורות `notifications` מהסורקים
 * בוורקר. המייל דורש את `EmailService` (סודות מוצפנים דרך הגדרות
 * הפלטפורמה), ולכן הוא רץ כאן, ב-API, כמו תזכורות ההפעלה
 * ‎(`ActivationNudgeService`) ומאותה סיבה.
 *
 * ## שני קצבים, מייל אחד
 *
 * „מיידי” = כל עשר דקות, כל מה שהצטרף מאז המייל הקודם — תגובה אחת
 * היא מייל אחד, אבל שרשור סוער הוא מייל אחד עם רשימה ולא עשרה.
 * „תקציר יומי” = פעם ביום ב-08:00 שעון ישראל, אותו מייל על היום
 * שחלף. החותמת `mailed_through` היא מה שמבטיח שדבר לא נשלח פעמיים
 * ודבר לא נופל בין הסבבים: היא מתקדמת רק אחרי שהספק קיבל.
 *
 * ## ומייל ההשקה
 *
 * מי שלחץ „עדכנו אותי” כשהפורום היה „בקרוב” נרשם ב-`feature_signups`.
 * ההבטחה הייתה „הודעה אחת, ביום ההשקה”; הסבב הראשון אחרי הפריסה
 * שולח אותה ומוחק את הרישום — המחיקה היא הסימון שההבטחה קוימה.
 */

const TICK_MS = 10 * 60 * 1000;
const FIRST_TICK_DELAY_MS = 2 * 60 * 1000;
/** כמה אחורה מסתכלים — מעבר לזה התראה שלא נשלחה מתיישנת ולא נשלחת. */
const LOOKBACK_MS = 3 * 24 * 60 * 60 * 1000;
/** שעת התקציר היומי — 08:00 שעון ישראל, כמו הסיכום השבועי. */
const DIGEST_HOUR = 8;
/** תקציר יומי לא נשלח פעמיים באותו יום גם אם הסבב חוזר בתוך השעה. */
const DIGEST_MIN_GAP_MS = 20 * 60 * 60 * 1000;
const MAX_SENDS_PER_SWEEP = 300;

@Injectable()
export class ForumMailService implements OnModuleInit, OnModuleDestroy {
  private readonly logger = new Logger(ForumMailService.name);
  private timer: NodeJS.Timeout | null = null;
  private first: NodeJS.Timeout | null = null;
  private running = false;

  constructor(
    private readonly prisma: PrismaService,
    private readonly email: EmailService,
  ) {}

  onModuleInit(): void {
    this.first = setTimeout(() => {
      void this.tick();
      this.timer = setInterval(() => void this.tick(), TICK_MS);
    }, FIRST_TICK_DELAY_MS);
    this.first.unref?.();
  }

  onModuleDestroy(): void {
    if (this.first) clearTimeout(this.first);
    if (this.timer) clearInterval(this.timer);
  }

  /**
   * האם מגיע למשתמש מייל עכשיו — פונקציה טהורה, נבדקת.
   *
   * „מיידי” — תמיד. „יומי” — רק בשעת התקציר, ורק אם לא נשלח היום.
   */
  static due(prefs: ForumPrefs, lastMailedAt: Date | null, now: Date): boolean {
    if (!prefs.email) return false;
    if (prefs.digest === "instant") return true;
    const hour = Number(jerusalemWallParts(now).time.slice(0, 2));
    if (hour !== DIGEST_HOUR) return false;
    return lastMailedAt === null || now.getTime() - lastMailedAt.getTime() >= DIGEST_MIN_GAP_MS;
  }

  async tick(now: Date = new Date()): Promise<number> {
    if (this.running) return 0;
    this.running = true;
    try {
      if (!(await this.email.isConfigured())) return 0;
      const launched = await this.sendLaunchMails();
      const sent = await this.sendActivityMails(now);
      return launched + sent;
    } catch (error: unknown) {
      this.logger.error(`סבב המייל של הפורום נכשל: ${String(error)}`);
      return 0;
    } finally {
      this.running = false;
    }
  }

  /** מייל ההשקה — למי שנרשם כשהפורום היה „בקרוב”, ואז מחיקת הרישום. */
  private async sendLaunchMails(): Promise<number> {
    const origin = loadEnv().WEB_ORIGIN;
    const tenants = await this.prisma.tenant.findMany({ select: { id: true } });
    let sent = 0;
    for (const tenant of tenants) {
      if (sent >= MAX_SENDS_PER_SWEEP) break;
      const signups = await this.prisma.withExplicitTenant(tenant.id, (tx) =>
        tx.featureSignup.findMany({ where: { tenantId: tenant.id, feature: "forum" }, select: { id: true, userId: true }, take: 50 }),
      );
      for (const signup of signups) {
        const user = await this.prisma.user.findFirst({
          where: { id: signup.userId, isActive: true },
          select: { name: true, email: true },
        });
        if (user !== null) {
          const mail = forumLaunchEmail(firstName(user.name), origin);
          try {
            await this.email.send(user.email, mail.subject, mail.content, { autoGenerated: true });
            sent += 1;
          } catch (error: unknown) {
            this.logger.warn(`מייל ההשקה של הפורום לא יצא: ${String(error)}`);
            continue; // הרישום נשאר — ננסה בסבב הבא
          }
        }
        await this.prisma.withExplicitTenant(tenant.id, (tx) => tx.featureSignup.delete({ where: { id: signup.id } }));
      }
    }
    return sent;
  }

  /** התראות הפורום שטרם נשלחו במייל — מייל אחד לכל משתמש. */
  private async sendActivityMails(now: Date): Promise<number> {
    const origin = loadEnv().WEB_ORIGIN;
    const since = new Date(now.getTime() - LOOKBACK_MS);
    const tenants = await this.prisma.tenant.findMany({
      where: { status: { in: ["active", "trial"] } },
      select: { id: true },
    });
    let sent = 0;
    for (const tenant of tenants) {
      if (sent >= MAX_SENDS_PER_SWEEP) break;
      const pending = await this.prisma.withExplicitTenant(tenant.id, (tx) =>
        tx.notification.findMany({
          where: { tenantId: tenant.id, type: { startsWith: "forum_" }, userId: { not: null }, createdAt: { gte: since } },
          orderBy: { createdAt: "asc" },
          select: { userId: true, type: true, title: true, body: true, entityId: true, createdAt: true },
        }),
      );
      if (pending.length === 0) continue;

      const byUser = new Map<string, typeof pending>();
      for (const row of pending) {
        if (row.userId === null || !isForumNotificationType(row.type)) continue;
        byUser.set(row.userId, [...(byUser.get(row.userId) ?? []), row]);
      }
      const users = await this.prisma.user.findMany({
        where: { id: { in: [...byUser.keys()] }, isActive: true },
        select: { id: true, name: true, email: true, preferences: true, forumMailState: true },
      });

      for (const user of users) {
        if (sent >= MAX_SENDS_PER_SWEEP) break;
        const prefs = parseForumPrefs(user.preferences);
        const state = user.forumMailState;
        if (!ForumMailService.due(prefs, state?.lastMailedAt ?? null, now)) continue;
        const mailedThrough = state?.mailedThrough ?? since;
        const fresh = (byUser.get(user.id) ?? []).filter((row) => row.createdAt > mailedThrough);
        if (fresh.length === 0) continue;

        const items: ForumMailItem[] = fresh.map((row) => ({
          type: row.type,
          title: row.title,
          body: row.body,
          threadId: row.entityId,
        }));
        const mail = forumActivityEmail(firstName(user.name), items, origin, prefs.digest);
        try {
          await this.email.send(user.email, mail.subject, mail.content, { autoGenerated: true });
        } catch (error: unknown) {
          this.logger.warn(`מייל הפורום לא יצא: ${String(error)}`);
          continue; // החותמת אינה זזה — הסבב הבא ינסה שוב
        }
        sent += 1;
        const through = fresh[fresh.length - 1]!.createdAt;
        await this.prisma.forumMailState.upsert({
          where: { userId: user.id },
          create: { userId: user.id, mailedThrough: through, lastMailedAt: now },
          update: { mailedThrough: through, lastMailedAt: now },
        });
      }
    }
    return sent;
  }
}

function firstName(name: string): string {
  return name.trim().split(/\s+/u)[0] ?? name;
}
