import {
  Injectable,
  Logger,
  type OnModuleDestroy,
  type OnModuleInit,
} from "@nestjs/common";
import { effectiveCapabilities, firstNameOf, pbxSilenceEmail } from "@metavchim/shared";
import { loadEnv } from "../../config/env";
import { EmailService } from "../../core/email.service";
import { PrismaService } from "../../core/prisma.service";

/**
 * ‎**„המרכזייה השתתקה” במייל — למי שאינו מחזיק מקום בסוכן בוואטסאפ.**
 *
 * ‏בקשת המשתמש: „רק מי שמנוי על הסוכן בוואטסאפ יקבל הודעה שהוובהוק
 * ‏במרכזייה כנראה לא פעיל; מי שלא מנוי יקבל רק את ההודעה במייל.”
 * ‏החצי של הוואטסאפ יושב ב-`whatsappNeedsSeat` (סבב ההתראות בעובדים),
 * ‏והחצי הזה משלים אותו: אותה שורת `notifications` שהסבב בעובדים
 * ‏כתב, בערוץ השלישי.
 *
 * ‏כאן ולא בעובדים — מאותה סיבה כמו `ForumMailService`: המייל דורש
 * ‏את `EmailService` (סודות מוצפנים דרך הגדרות הפלטפורמה).
 *
 * ## מי מקבל
 *
 * ‏משתמש פעיל בלי מקום בסוכן, **שרשאי לתקן** (`settings.manage` —
 * ‏אותה יכולת שהקישור בהתראה דורש). סוכן שאינו יכול לגשת להגדרות
 * ‏המרכזייה אינו מקבל מייל שאין לו מה לעשות איתו; הפעמון נשאר אצלו
 * ‏כמו היום.
 *
 * ## למה אין כאן חותמת „נשלח עד”
 *
 * ‏ההתראה נכתבת פעם ביום לכל היותר (`pbxSilenceDedupeKey`), ולכן
 * ‏המפתח של `EmailService` — התראה ונמען — הוא כל הזיכרון הנדרש:
 * ‏סבב שחוזר על אותה התראה מקבל „כבר יצא” ואינו שולח שוב.
 */

const TICK_MS = 10 * 60 * 1000;
const FIRST_TICK_DELAY_MS = 3 * 60 * 1000;
/**
 * ‏כמה אחורה מסתכלים. המייל אמור להגיע בתוך דקות מההתראה; מעבר לזה
 * ‏(API שהיה למטה חצי יום) הוא כבר אינו חדשות, והפעמון מציג אותה.
 */
const LOOKBACK_MS = 6 * 60 * 60 * 1000;

@Injectable()
export class PbxSilenceMailService implements OnModuleInit, OnModuleDestroy {
  private readonly logger = new Logger(PbxSilenceMailService.name);
  private timer: NodeJS.Timeout | null = null;
  private first: NodeJS.Timeout | null = null;
  private running = false;

  constructor(
    private readonly prisma: PrismaService,
    private readonly email: EmailService,
  ) {}

  onModuleInit(): void {
    this.first = setTimeout(() => {
      void this.tick();
      this.timer = setInterval(() => void this.tick(), TICK_MS);
    }, FIRST_TICK_DELAY_MS);
    this.first.unref?.();
  }

  onModuleDestroy(): void {
    if (this.first) clearTimeout(this.first);
    if (this.timer) clearInterval(this.timer);
  }

  /** סבב אחד. ציבורי כדי שבדיקה תוכל להריץ אותו בלי לחכות. */
  async tick(now: Date = new Date()): Promise<void> {
    if (this.running) return;
    this.running = true;
    try {
      if (!(await this.email.isConfigured())) return;
      await this.sendPending(now);
    } catch (error: unknown) {
      this.logger.error(`סבב המייל על שתיקת המרכזייה נכשל: ${String(error)}`);
    } finally {
      this.running = false;
    }
  }

  private async sendPending(now: Date): Promise<void> {
    const origin = loadEnv().WEB_ORIGIN;
    const since = new Date(now.getTime() - LOOKBACK_MS);
    const tenants = await this.prisma.tenant.findMany({
      where: { status: { in: ["active", "trial"] } },
      select: { id: true, blockedModules: true },
    });

    for (const tenant of tenants) {
      const alerts = await this.prisma.withExplicitTenant(tenant.id, (tx) =>
        tx.notification.findMany({
          where: { tenantId: tenant.id, type: "pbx_silent", createdAt: { gte: since } },
          select: { id: true, title: true, body: true },
        }),
      );
      if (alerts.length === 0) continue;

      const recipients = await this.recipients(tenant.id, tenant.blockedModules, now);
      for (const alert of alerts) {
        for (const user of recipients) {
          const mail = pbxSilenceEmail({
            firstName: firstNameOf(user.name),
            title: alert.title,
            body: alert.body,
            webOrigin: origin,
          });
          try {
            await this.email.send(user.email, mail.subject, mail.content, {
              idempotency: { key: `pbxsilent:${alert.id}:${user.id}`, purpose: "pbx_silent" },
              autoGenerated: true,
            });
          } catch (error: unknown) {
            // ‏המפתח לא נסגר — הסבב הבא ינסה שוב
            this.logger.warn(`מייל שתיקת המרכזייה לא יצא: ${String(error)}`);
          }
        }
      }
    }
  }

  /**
   * ‏מנהלי המשרד שאין להם מקום בסוכן — ראו „מי מקבל” למעלה.
   *
   * ‏החריגים נקראים בתוך הקשר הדייר: `user_capabilities` תחת RLS,
   * ‏ושאילתה בלעדיו מחזירה אפס שורות בשקט — מנהל שהיכולת שלו הוענקה
   * ‏בחריג לא היה מקבל את המייל.
   */
  private async recipients(
    tenantId: string,
    blockedModules: readonly string[],
    now: Date,
  ): Promise<{ id: string; name: string; email: string }[]> {
    const staff = await this.prisma.user.findMany({
      where: { tenantId, isActive: true, whatsappAccess: false },
      select: { id: true, name: true, email: true, role: true },
    });
    if (staff.length === 0) return [];
    const overrides = await this.prisma.withExplicitTenant(tenantId, (tx) =>
      tx.userCapability.findMany({
        where: { tenantId, userId: { in: staff.map((user) => user.id) } },
        select: { userId: true, capability: true, effect: true, expiresAt: true },
      }),
    );
    return staff.filter((user) =>
      effectiveCapabilities(
        {
          role: user.role,
          overrides: overrides.filter((row) => row.userId === user.id),
          blockedModules,
        },
        now,
      ).has("settings.manage"),
    );
  }
}
